package com.initialization.example.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	//@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	//private UserService userService;

	@RequestMapping("/index")
	public String test(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model){
		model.addAttribute("name", name);
		return "index";
	}
	
}